08-06-2025

Pandas

1.pandas is a python library
2.used for a handling the larger dataets
3. the pandas library provides the data structures and operations for manipulating the numerical tables
4.its an open source released under the 3-clause BSD license.
5.It process, manipulate tabuler data, implementing operations such as loading,merging,transforming,grouping data sets effectively

In [1]:
#1st step is to install pandas library
!pip3 install pandas

Requirement already satisfied: pandas in c:\users\bhava\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\bhava\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bhava\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\bhava\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\bhava\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\bhava\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#importing pandas 
import pandas as pd
#checking package version
pd.__version__

'2.2.3'

In [3]:
#reading the csv data from csv fille and then loading into Dataframe
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
print(df)

                  area_type   availability       size  society total_sqft  \
0      Super built-up  Area         19-Dec      2 BHK  Coomee        1056
1                Plot  Area  Ready To Move  4 Bedroom  Theanmp       2600
2            Built-up  Area  Ready To Move      3 BHK      NaN       1440
3      Super built-up  Area  Ready To Move      3 BHK  Soiewre       1521
4      Super built-up  Area  Ready To Move      2 BHK      NaN       1200
...                     ...            ...        ...      ...        ...
13315        Built-up  Area  Ready To Move  5 Bedroom  ArsiaEx       3453
13316  Super built-up  Area  Ready To Move      4 BHK      NaN       3600
13317        Built-up  Area  Ready To Move      2 BHK  Mahla T       1141
13318  Super built-up  Area         18-Jun      4 BHK  SollyCl       4689
13319  Super built-up  Area  Ready To Move      1 BHK      NaN        550

       bath  balcony   price         site_location
0       2.0      1.0   39.07           Alandi Road
1       5.0      3.0  120.00       Ambegaon Budruk
2       2.0      3.0   62.00            Anandnagar
3       3.0      1.0   95.00                 Aundh
4       2.0      1.0   51.00            Aundh Road
...     ...      ...     ...                   ...
13315   4.0      0.0  231.00                Pashan
13316   5.0      NaN  400.00             Paud Road
13317   2.0      1.0   60.00              Pirangut
13318   4.0      1.0  488.00          Prabhat Road
13319   1.0      1.0   17.00  Pune Railway Station

[13320 rows x 9 columns]

In [4]:
#checking the column names
import pandas as pd
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
df.columns

Index(['area_type', 'availability', 'size', 'society', 'total_sqft', 'bath',
       'balcony', 'price', 'site_location'],
      dtype='object')

In [ ]:
#checking type
print(type(df))

In [ ]:
#checking index range and how many jumps
df.index

In [ ]:
#extract the single row
df.loc[13000]

In [6]:
#extracting the rows from multiple rows
df.loc[0:2000]

,area_type,availability,size,society,total_sqft,bath,balcony,price,site_location
0,Super built-up Area,19-Dec,2 BHK,Coomee,1056,2.0,1.0,39.07,Alandi Road
1,Plot Area,Ready To Move,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,Ambegaon Budruk
2,Built-up Area,Ready To Move,3 BHK,NaN,1440,2.0,3.0,62.00,Anandnagar
3,Super built-up Area,Ready To Move,3 BHK,Soiewre,1521,3.0,1.0,95.00,Aundh
4,Super built-up Area,Ready To Move,2 BHK,NaN,1200,2.0,1.0,51.00,Aundh Road
...,...,...,...,...,...,...,...,...,...
1996,Built-up Area,Ready To Move,2 BHK,Siise R,850,2.0,1.0,33.00,Salunke Vihar
1997,Super built-up Area,19-Oct,1 BHK,NaN,530,1.0,1.0,18.00,Sasson Road
1998,Super built-up Area,18-Jul,3 BHK,NaN,1550,3.0,3.0,110.00,Satara Road
1999,Super built-up Area,19-Dec,3 BHK,GoityEt,1699,3.0,3.0,97.00,Senapati Bapat Road
2000,Super built-up Area,17-Oct,4 BHK,NiCodCa,2025,4.0,3.0,109.00,Shaniwar Peth

In [ ]:
#fetching data from particular row
import pandas as pd
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
a=df.iloc[0:20,1:3]
print(a)

In [ ]:
#extract column info
df['area_type']

In [ ]:
#fetching data from a specific rows and specific columns continous index
import pandas as pd
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
df[['area_type', 'availability', 'size','price']]
df.iloc[2000:6000,2:7]

           size  society total_sqft  bath  balcony
2000      4 BHK  NiCodCa       2025   4.0      3.0
2001      1 BHK      NaN        500   2.0      2.0
2002      1 BHK  Jeshan         500   1.0      0.0
2003      2 BHK      NaN       1146   2.0      1.0
2004      3 BHK  Sariaat       2475   4.0      3.0
...         ...      ...        ...   ...      ...
5995      2 BHK  DNncasa       1274   2.0      1.0
5996  2 Bedroom      NaN        600   1.0      1.0
5997      3 BHK  KencyRe       1430   2.0      1.0
5998  4 Bedroom      NaN       1800   2.0      0.0
5999      3 BHK  Dhalsh        1565   2.0      2.0

[4000 rows x 5 columns]

In [ ]:
#fetching data row vise and column wise- specific colums and specific rows data
import pandas as pd
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
df[['area_type','availability', 'size','price']]
a=df.iloc[[200,300,400,2000,10000],[2,5,8]]
print(a)

        size  bath    site_location
200    2 BHK   2.0  Bhandarkar Road
300    4 BHK   3.0     Budhwar Peth
400    3 BHK   3.0           Dapodi
2000   4 BHK   4.0    Shaniwar Peth
10000  2 BHK   1.0    Chandan Nagar

In [ ]:
#extracting data based on condition
import pandas as pd
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
b=df['price']>=30 
print(b)

0         True
1         True
2         True
3         True
4         True
         ...
13315     True
13316     True
13317     True
13318     True
13319    False
Name: price, Length: 13320, dtype: bool

In [7]:
#extracting data by mul conditions
import pandas as pd
df=pd.read_csv(r'C:\Users\bhava\GUVI\Code\Data\Punehousedata.csv')
condition1=df['area_type']=='Built-up Area'
condition2=df['price']>=20
print(condition1 & condition2)
print(condition1 | condition2)
condition3=df['area_type']!='Built-up Area'
condition3

0        False
1        False
2        False
3        False
4        False
         ...
13315    False
13316    False
13317    False
13318    False
13319    False
Length: 13320, dtype: bool
0         True
1         True
2         True
3         True
4         True
         ...
13315     True
13316     True
13317     True
13318     True
13319    False
Length: 13320, dtype: bool

0        True
1        True
2        True
3        True
4        True
         ...
13315    True
13316    True
13317    True
13318    True
13319    True
Name: area_type, Length: 13320, dtype: bool

In [11]:
#count how many times the specific row appering in specific column
df['area_type'].value_counts()
df['availability'].value_counts().sort_values()

availability
15-Jun               1
15-Dec               1
16-Jul               1
15-Aug               1
16-Oct               1
                 ...
18-Aug             200
18-Apr             271
18-May             295
18-Dec             307
Ready To Move    10581
Name: count, Length: 81, dtype: int64

In [ ]:
#find the different values avilable or unique data in specififc column
#tuple of array dimentions-->df.shape
different_values_avilable=df['price'].unique()
print(different_values_avilable)
#sorting data in specific colum ascendeng
df[['availability','site_location']].sort_values

[ 39.07 120.    62.   ...  40.14 231.   488.  ]

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [36]:
#fetching top5 records
df.head(5)
#fetching buttom 10 rows
df.tail(10)

,area_type,availability,size,society,total_sqft,bath,balcony,price,site_location
13310,Super built-up Area,Ready To Move,2 BHK,NaN,1050,2.0,2.0,52.71,Narayan Peth
13311,Plot Area,Ready To Move,7 Bedroom,NaN,1500,9.0,2.0,250.00,Narayangaon
13312,Super built-up Area,Ready To Move,2 BHK,NaN,1262,2.0,2.0,47.00,Navi Peth
13313,Super built-up Area,Ready To Move,3 BHK,Aklia R,1345,2.0,1.0,57.00,Padmavati
13314,Super built-up Area,Ready To Move,3 BHK,SoosePr,1715,3.0,3.0,112.00,Parvati Darshan
13315,Built-up Area,Ready To Move,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00,Pashan
13316,Super built-up Area,Ready To Move,4 BHK,NaN,3600,5.0,NaN,400.00,Paud Road
13317,Built-up Area,Ready To Move,2 BHK,Mahla T,1141,2.0,1.0,60.00,Pirangut
13318,Super built-up Area,18-Jun,4 BHK,SollyCl,4689,4.0,1.0,488.00,Prabhat Road
13319,Super built-up Area,Ready To Move,1 BHK,NaN,550,1.0,1.0,17.00,Pune Railway Station

In [40]:
#get summary of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   area_type      13320 non-null  object
 1   availability   13320 non-null  object
 2   size           13304 non-null  object
 3   society        7818 non-null   object
 4   total_sqft     13320 non-null  object
 5   bath           13247 non-null  float64
 6   balcony        12711 non-null  float64
 7   price          13320 non-null  float64
 8   site_location  13319 non-null  object
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [41]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [42]:
#Create Dataframe
data={
'name':['bhavana','krushi','zuppi','GiriMama','Shiva prasad','Sujatha','Rajani','narayanappa','PramodMama'],
'age':[24,20,27,27,17,40,32,59,32],
'location':['kolar','kolar','banglore','banglore','chennai','kolar','kolar','banglore','chennai'],
'email':['bhavana@gmail.com','krushi@gmail.com','zuppi@gmail.com','GiriMama@gmail.com','Shivaprasad@gmail.com','Sujatha@gmail.com','Rajani@gmail.com','narayanappa@gmail.com','PramodMama@gmail.com'],
'Course':['AIML','AIML','Accounts','Agriculture','Science','Housewife','Agriculture','Agriculture','ITI'],
'height':[5.2,5.2,5.1,5.6,6,5.2,4.9,5.6,6]
}
df=pd.DataFrame(data)
df

           name  age  location                  email       Course  height
0       bhavana   24     kolar      bhavana@gmail.com         AIML     5.2
1        krushi   20     kolar       krushi@gmail.com         AIML     5.2
2         zuppi   27  banglore        zuppi@gmail.com     Accounts     5.1
3      GiriMama   27  banglore     GiriMama@gmail.com  Agriculture     5.6
4  Shiva prasad   17   chennai  Shivaprasad@gmail.com      Science     6.0
5       Sujatha   40     kolar      Sujatha@gmail.com    Housewife     5.2
6        Rajani   32     kolar       Rajani@gmail.com  Agriculture     4.9
7   narayanappa   59  banglore  narayanappa@gmail.com  Agriculture     5.6
8    PramodMama   32   chennai   PramodMama@gmail.com          ITI     6.0

In [44]:
df.columns

Index(['name', 'age', 'location', 'email', 'Course', 'height'], dtype='object')

In [47]:
df.describe()

             age    height
count   9.000000  9.000000
mean   30.888889  5.422222
std    12.574224  0.396162
min    17.000000  4.900000
25%    24.000000  5.200000
50%    27.000000  5.200000
75%    32.000000  5.600000
max    59.000000  6.000000

In [48]:
df.head(5)

           name  age  location                  email       Course  height
0       bhavana   24     kolar      bhavana@gmail.com         AIML     5.2
1        krushi   20     kolar       krushi@gmail.com         AIML     5.2
2         zuppi   27  banglore        zuppi@gmail.com     Accounts     5.1
3      GiriMama   27  banglore     GiriMama@gmail.com  Agriculture     5.6
4  Shiva prasad   17   chennai  Shivaprasad@gmail.com      Science     6.0

In [49]:
df.loc[0:4]

           name  age  location                  email       Course  height
0       bhavana   24     kolar      bhavana@gmail.com         AIML     5.2
1        krushi   20     kolar       krushi@gmail.com         AIML     5.2
2         zuppi   27  banglore        zuppi@gmail.com     Accounts     5.1
3      GiriMama   27  banglore     GiriMama@gmail.com  Agriculture     5.6
4  Shiva prasad   17   chennai  Shivaprasad@gmail.com      Science     6.0

In [51]:
df.iloc[1:5,[1,5]]

   age  height
1   20     5.2
2   27     5.1
3   27     5.6
4   17     6.0

In [53]:
df['location'].unique()

array(['kolar', 'banglore', 'chennai'], dtype=object)

In [54]:
df['age']<=20

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7    False
8    False
Name: age, dtype: bool

In [56]:
condition1=df['age']>=30
condition2=df['location']=='kolar'
(condition2 & condition1)

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7    False
8    False
dtype: bool

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      9 non-null      object
 1   age       9 non-null      int64
 2   location  9 non-null      object
 3   email     9 non-null      object
 4   Course    9 non-null      object
 5   height    9 non-null      float64
dtypes: float64(1), int64(1), object(4)
memory usage: 564.0+ bytes

In [63]:
df.tail(4)

          name  age  location                  email       Course  height
5      Sujatha   40     kolar      Sujatha@gmail.com    Housewife     5.2
6       Rajani   32     kolar       Rajani@gmail.com  Agriculture     4.9
7  narayanappa   59  banglore  narayanappa@gmail.com  Agriculture     5.6
8   PramodMama   32   chennai   PramodMama@gmail.com          ITI     6.0

In [82]:
# merge two data sets
import pandas as pd
data1={
    'name':['a','b','c','d','e'],
    'age':['123','200','300','400','500'],
    'location':['abc','efg','hig','klm','nop'],
    'email':['a@gmail.com','b@gmail.com','c@gmail.com','d@gmail.com','e@gmail.com'],
}
df1=pd.DataFrame(data1)
data2={
    'email':['f@gmail.com','g@gmail.com','h@gmail.com','d@gmail.com','e@gmail.com'],
     'height':[1,2,3,4,5],
    'position':['xyz','xyz','pqr','stu','vwx']
}
df2=pd.DataFrame(data2)
#print(f'{df2} \n{df1}')
pd.concat([df1,df2],axis=1)

  name  age location        email        email  height position
0    a  123      abc  a@gmail.com  f@gmail.com       1      xyz
1    b  200      efg  b@gmail.com  g@gmail.com       2      xyz
2    c  300      hig  c@gmail.com  h@gmail.com       3      pqr
3    d  400      klm  d@gmail.com  d@gmail.com       4      stu
4    e  500      nop  e@gmail.com  e@gmail.com       5      vwx

In [73]:
pd.concat([df1,df2],axis=1)

  name  age location        email  height position
0    a  123      abc  a@gmail.com       1      xyz
1    b  200      efg  b@gmail.com       2      xyz
2    c  300      hig  c@gmail.com       3      pqr
3    d  400      klm  d@gmail.com       4      stu
4    e  500      nop  e@gmail.com       5      vwx

In [80]:
#merge data using left side
pd.merge(df1,df2,on='email',how='left')

  name  age location        email  height position
0    a  123      abc  a@gmail.com     NaN      NaN
1    b  200      efg  b@gmail.com     NaN      NaN
2    c  300      hig  c@gmail.com     NaN      NaN
3    d  400      klm  d@gmail.com     4.0      stu
4    e  500      nop  e@gmail.com     5.0      vwx

In [83]:
pd.merge(df1,df2,on='email',how='right')

  name  age location        email  height position
0  NaN  NaN      NaN  f@gmail.com       1      xyz
1  NaN  NaN      NaN  g@gmail.com       2      xyz
2  NaN  NaN      NaN  h@gmail.com       3      pqr
3    d  400      klm  d@gmail.com       4      stu
4    e  500      nop  e@gmail.com       5      vwx

In [84]:
#grouping the data
data={
'name':['bhavana','krushi','zuppi','GiriMama','Shiva prasad','Sujatha','Rajani','narayanappa','PramodMama'],
'age':[24,20,27,27,17,40,32,59,32],
'location':['kolar','kolar','banglore','banglore','chennai','kolar','kolar','banglore','chennai'],
'email':['bhavana@gmail.com','krushi@gmail.com','zuppi@gmail.com','GiriMama@gmail.com','Shivaprasad@gmail.com','Sujatha@gmail.com','Rajani@gmail.com','narayanappa@gmail.com','PramodMama@gmail.com'],
'Course':['AIML','AIML','Accounts','Agriculture','Science','Housewife','Agriculture','Agriculture','ITI'],
'height':[5.2,5.2,5.1,5.6,6,5.2,4.9,5.6,6]
}
grouped_data=df.groupby(['height'])
for name,data in grouped_data:
    print(f'{name}\n{data}')

(4.9,)
     name  age location             email       Course  height
6  Rajani   32    kolar  Rajani@gmail.com  Agriculture     4.9
(5.1,)
    name  age  location            email    Course  height
2  zuppi   27  banglore  zuppi@gmail.com  Accounts     5.1
(5.2,)
      name  age location              email     Course  height
0  bhavana   24    kolar  bhavana@gmail.com       AIML     5.2
1   krushi   20    kolar   krushi@gmail.com       AIML     5.2
5  Sujatha   40    kolar  Sujatha@gmail.com  Housewife     5.2
(5.6,)
          name  age  location                  email       Course  height
3     GiriMama   27  banglore     GiriMama@gmail.com  Agriculture     5.6
7  narayanappa   59  banglore  narayanappa@gmail.com  Agriculture     5.6
(6.0,)
           name  age location                  email   Course  height
4  Shiva prasad   17  chennai  Shivaprasad@gmail.com  Science     6.0
8    PramodMama   32  chennai   PramodMama@gmail.com      ITI     6.0

In [ ]:
#group the data based on location
data={
'name':['bhavana','krushi','zuppi','GiriMama','Shiva prasad','Sujatha','Rajani','narayanappa','PramodMama'],
'age':[24,20,27,27,17,40,32,59,32],
'location':['kolar','kolar','banglore','banglore','chennai','kolar','kolar','banglore','chennai'],
'email':['bhavana@gmail.com','krushi@gmail.com','zuppi@gmail.com','GiriMama@gmail.com','Shivaprasad@gmail.com','Sujatha@gmail.com','Rajani@gmail.com','narayanappa@gmail.com','PramodMama@gmail.com'],
'Course':['AIML','AIML','Accounts','Agriculture','Science','cooking ','Agriculture','Agriculture','ITI'],
'height':[5.2,5.2,5.1,5.6,6,5.2,4.9,5.6,6]
}
grouped_data=df.groupby(['location'])
for location,data in grouped_data:
    print(f'{name}\n{location}\n{data}')

(6.0,)
('banglore',)
          name  age  location                  email       Course  height
2        zuppi   27  banglore        zuppi@gmail.com     Accounts     5.1
3     GiriMama   27  banglore     GiriMama@gmail.com  Agriculture     5.6
7  narayanappa   59  banglore  narayanappa@gmail.com  Agriculture     5.6
(6.0,)
('chennai',)
           name  age location                  email   Course  height
4  Shiva prasad   17  chennai  Shivaprasad@gmail.com  Science     6.0
8    PramodMama   32  chennai   PramodMama@gmail.com      ITI     6.0
(6.0,)
('kolar',)
      name  age location              email       Course  height
0  bhavana   24    kolar  bhavana@gmail.com         AIML     5.2
1   krushi   20    kolar   krushi@gmail.com         AIML     5.2
5  Sujatha   40    kolar  Sujatha@gmail.com    Housewife     5.2
6   Rajani   32    kolar   Rajani@gmail.com  Agriculture     4.9

In [91]:
#finding avg value based on column name
df['age'].mean()
print(f'avrage value of {name}:{data['age'].mean()}')
print(f'median height for {name}:{data['height'].median}')

avrage value of (6.0,):29.0
median height for (6.0,):<bound method Series.median of 0    5.2
1    5.2
5    5.2
6    4.9
Name: height, dtype: float64>

In [93]:
df['height'].median()

np.float64(5.2)

In [95]:
df['location'].mode()

0    kolar
Name: location, dtype: object

In [96]:
df['location'].std

<bound method Series.std of 0       kolar
1       kolar
2    banglore
3    banglore
4     chennai
5       kolar
6       kolar
7    banglore
8     chennai
Name: location, dtype: object>

In [99]:
grouped_data=df.groupby(['location','height'])
print(grouped_data)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001C5C40800B0>

In [106]:
#performing action using agg func
grouped_data=df.groupby(['location','Course','name']).agg({
 'age':['mean','median','min','max','sum'],
 'height':['median','sum']   
})
grouped_data

                                    age                    height
                                   mean median min max sum median  sum
location Course      name
banglore Accounts    zuppi         27.0   27.0  27  27  27    5.1  5.1
         Agriculture GiriMama      27.0   27.0  27  27  27    5.6  5.6
                     narayanappa   59.0   59.0  59  59  59    5.6  5.6
chennai  ITI         PramodMama    32.0   32.0  32  32  32    6.0  6.0
         Science     Shiva prasad  17.0   17.0  17  17  17    6.0  6.0
kolar    AIML        bhavana       24.0   24.0  24  24  24    5.2  5.2
                     krushi        20.0   20.0  20  20  20    5.2  5.2
         Agriculture Rajani        32.0   32.0  32  32  32    4.9  4.9
         Housewife   Sujatha       40.0   40.0  40  40  40    5.2  5.2

In [108]:
#Groupping the data by applying condition/filters
grouped_data=df.groupby(['name','age','height','location']).filter(lambda x:x['age'].mean()>=30)
grouped_data

          name  age  location                  email       Course  height
5      Sujatha   40     kolar      Sujatha@gmail.com    Housewife     5.2
6       Rajani   32     kolar       Rajani@gmail.com  Agriculture     4.9
7  narayanappa   59  banglore  narayanappa@gmail.com  Agriculture     5.6
8   PramodMama   32   chennai   PramodMama@gmail.com          ITI     6.0

In [110]:
#pivot table ---its converting already existing columns to new columns
pivot=pd.pivot(df,index='name',columns='location',values='email')
pivot

location                   banglore                chennai              kolar
name
GiriMama         GiriMama@gmail.com                    NaN                NaN
PramodMama                      NaN   PramodMama@gmail.com                NaN
Rajani                          NaN                    NaN   Rajani@gmail.com
Shiva prasad                    NaN  Shivaprasad@gmail.com                NaN
Sujatha                         NaN                    NaN  Sujatha@gmail.com
bhavana                         NaN                    NaN  bhavana@gmail.com
krushi                          NaN                    NaN   krushi@gmail.com
narayanappa   narayanappa@gmail.com                    NaN                NaN
zuppi               zuppi@gmail.com                    NaN                NaN

In [ ]:
#Apply indivisual data
#checking avg age based on course(AIML,science ect)
import pandas as pd
data={
'name':['bhavana','krushi','zuppi','GiriMama','Shiva prasad','Sujatha','Rajani','narayanappa','PramodMama'],
'age':[24,20,27,27,17,40,32,59,32],
'location':['kolar','kolar','banglore','banglore','chennai','kolar','kolar','banglore','chennai'],
'email':['bhavana@gmail.com','krushi@gmail.com','zuppi@gmail.com','GiriMama@gmail.com','Shivaprasad@gmail.com','Sujatha@gmail.com','Rajani@gmail.com','narayanappa@gmail.com','PramodMama@gmail.com'],
'Course':['AIML','AIML','Accounts','Agriculture','Science','Housewife','Agriculture','Agriculture','ITI'],
'height':[5.2,5.2,5.1,5.6,6,5.2,4.9,5.6,6]
}
df=pd.DataFrame(data)
grouped_data=df.groupby(['Course'])
for grouped_Course,data in grouped_data:
 print(f"Mean: \naverage age of {grouped_Course}:{data['age'].mean()} \nMedian: \nmedian height for {grouped_Course}:{data['height'].median()}")
a=df.groupby(['Course','location']).sum()
print(f'sum of course and loaction by groupes:{a}')

Mean:
average age of ('AIML',):22.0
Median:
median height for ('AIML',):5.2
Mean:
average age of ('Accounts',):27.0
Median:
median height for ('Accounts',):5.1
Mean:
average age of ('Agriculture',):39.333333333333336
Median:
median height for ('Agriculture',):5.6
Mean:
average age of ('Housewife',):40.0
Median:
median height for ('Housewife',):5.2
Mean:
average age of ('ITI',):32.0
Median:
median height for ('ITI',):6.0
Mean:
average age of ('Science',):17.0
Median:
median height for ('Science',):6.0
sum of course and loaction by groupes:                                     name  age  \
Course      location
AIML        kolar           bhavanakrushi   44
Accounts    banglore                zuppi   27
Agriculture banglore  GiriMamanarayanappa   86
            kolar                  Rajani   32
Housewife   kolar                 Sujatha   40
ITI         chennai            PramodMama   32
Science     chennai          Shiva prasad   17

                                                        email  height
Course      location
AIML        kolar           bhavana@gmail.comkrushi@gmail.com    10.4
Accounts    banglore                          zuppi@gmail.com     5.1
Agriculture banglore  GiriMama@gmail.comnarayanappa@gmail.com    11.2
            kolar                            Rajani@gmail.com     4.9
Housewife   kolar                           Sujatha@gmail.com     5.2
ITI         chennai                      PramodMama@gmail.com     6.0
Science     chennai                     Shivaprasad@gmail.com     6.0

In [ ]:
# find the average value based on column name
data={
'name':['bhavana','krushi','zuppi','GiriMama','Shiva prasad','Sujatha','Rajani','narayanappa','PramodMama'],
'age':[24,20,27,27,17,40,32,59,32],
'location':['kolar','kolar','banglore','banglore','chennai','kolar','kolar','banglore','chennai'],
'email':['bhavana@gmail.com','krushi@gmail.com','zuppi@gmail.com','GiriMama@gmail.com','Shivaprasad@gmail.com','Sujatha@gmail.com','Rajani@gmail.com','narayanappa@gmail.com','PramodMama@gmail.com'],
'Course':['AIML','AIML','Accounts','Agriculture','Science','Housewife','Agriculture','Agriculture','ITI'],
'height':[5.2,5.2,5.1,5.6,6,5.2,4.9,5.6,6]
}
df=pd.DataFrame(data)
avg_age=df['age'].mean()
avg_age

np.float64(30.88888888888889)

In [41]:
#Apply indivisual data
#checking sum for course anf=d location
import pandas as pd
data={
'name':['bhavana','krushi','zuppi','GiriMama','Shiva prasad','Sujatha','Rajani','narayanappa','PramodMama'],
'age':[24,20,27,27,17,40,32,59,32],
'location':['kolar','kolar','banglore','banglore','chennai','kolar','kolar','banglore','chennai'],
'email':['bhavana@gmail.com','krushi@gmail.com','zuppi@gmail.com','GiriMama@gmail.com','Shivaprasad@gmail.com','Sujatha@gmail.com','Rajani@gmail.com','narayanappa@gmail.com','PramodMama@gmail.com'],
'Course':['AIML','AIML','Accounts','Agriculture','Science','Housewife','Agriculture','Agriculture','ITI'],
'height':[5.2,5.2,5.1,5.6,6,5.2,4.9,5.6,6]
}
df=pd.DataFrame(data)
a=df.groupby(['Course','location']).sum(['age','height'])
print(f'sum of course and loaction by groupes:{a}')

sum of course and loaction by groupes:                      age  height
Course      location
AIML        kolar      44    10.4
Accounts    banglore   27     5.1
Agriculture banglore   86    11.2
            kolar      32     4.9
Housewife   kolar      40     5.2
ITI         chennai    32     6.0
Science     chennai    17     6.0